### ISSUE TITLE
Terraform v0.12.7 unsupported block type

### ISSUE THREAD

**Issue by ax-cgray** [CloudHealth/terraform-cloudhealth-iam#22]
When attempting to run my terraform apply, I'm running into unsupported block type issues. I also experienced the issues described in the following PR and was able to make the manual modifications to put POLICY on a new line, which did get me past that initial hurdle.

https://github.com/CloudHealth/terraform-cloudhealth-iam/pull/21

Here's the logs:

terraform apply

Error: Unsupported block type

  on .terraform/modules/cloudhealth-iam-role/role/role.tf line 15, in data "template_file" "default-s3-billing-bucket-policy":
  15:   vars {

Blocks of type "vars" are not expected here. Did you mean to define argument
"vars"? If so, use the equals sign to assign it a value.

Error: Unsupported block type

  on .terraform/modules/cloudhealth-iam-role/role/role.tf line 32, in data "template_file" "default-s3-cloudtrail-bucket-policy":
  32:   vars {

Blocks of type "vars" are not expected here. Did you mean to define argument
"vars"? If so, use the equals sign to assign it a value.

Error: Unsupported block type

  on .terraform/modules/cloudhealth-iam-role/role/role.tf line 49, in data "template_file" "default-s3-cur-bucket-policy":
  49:   vars {

Blocks of type "vars" are not expected here. Did you mean to define argument
"vars"? If so, use the equals sign to assign it a value.

Error: Unsupported block type

  on .terraform/modules/cloudhealth-iam-role/role/role.tf line 66, in data "template_file" "default-s3-config-bucket-policy":
  66:   vars {

Blocks of type "vars" are not expected here. Did you mean to define argument
"vars"? If so, use the equals sign to assign it a value.

Error: Unsupported block type

  on .terraform/modules/cloudhealth-iam-role/role/role.tf line 83, in data "template_file" "default-s3-ecs-bucket-policy":
  83:   vars {

Blocks of type "vars" are not expected here. Did you mean to define argument
"vars"? If so, use the equals sign to assign it a value.

**Comment by chussenot** [comment]
Hello, have you plan to upgrade this module to tf 12 @angelconcepcion ?

**Comment by bateller** [comment]
This issue is now resolved via this PR: https://github.com/CloudHealth/terraform-cloudhealth-iam/pull/30
