### ISSUE TITLE
Please fix IAM policy

### ISSUE THREAD

**Issue by stremovsky** [CloudHealth/terraform-cloudhealth-iam#41]
Hello guys

We are getting AWS IAM warning because of CloudHealth in our environment.

Take a look at this screenshot:

![policy-warning](https://user-images.githubusercontent.com/13130594/216788638-188d1efd-0cf9-446a-9268-28d85d7a98ee.png)

Affected file: ``role/inputs.tf``
Line to address: ``"aws-portal:ViewBilling",``

**Comment by angelconcepcion** [comment]
Hi all, will be looking into this today and should get a fix out.
